name: Deploy
on:
  workflow_dispatch:
    inputs:
      modules:
        description: modules do you want build separate by space
        required: false
        default: ''
  pull_request_target:
    types:
      - closed
    branches:
      - develop
      - main

permissions: write-all

jobs:
  context:
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    runs-on:
      - self-hosted
      - Linux
      - pmeig
    steps:
      - name: checkout project
        uses: actions/checkout@v4
      - name: metadata
        id: metadata
        uses: pmeig/github-actions/actions/context/metadata@main
      - name: retrieve module change
        id: modules-accepted
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: pmeig/github-actions/actions/github/diff@main
        with:
          includes: 'start=projects'
          parent: 'true'
      - name: retrieve modules change
        id: changed
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          names=''
          for module in ${{ steps.modules-accepted.outputs.parents }}
          do
            name=$(jq -rc --arg path "$module" '.projects | to_entries | map(select(.value.root == $path)) | .[] | .key' angular.json)
            names="$names $name"
          done
          echo "value=$names" >> $GITHUB_OUTPUT
      - name: suffix version
        id: suffix
        uses: pmeig/github-actions/actions/context/version/suffix@main
        with:
          env: ${{ steps.metadata.outputs.env-target }}
      - name: env accepted
        id: env
        run: |
          env='${{ steps.metadata.outputs.env-target }}'
          if [ '${{ github.event_name }}' == 'workflow_dispatch' ]
          then
            env='dev'
          fi
          echo "value=$env" >> $GITHUB_OUTPUT
      - name: build matrix
        id: matrix
        run: |
          json='[]'
          names='${{ steps.changed.outputs.value }}${{ inputs.modules }}'
          projects=$(jq -rc '.projects | to_entries | map({ (.key): .value.root}) | reduce .[] as $item ({}; . + $item)' angular.json)
          value='{}'
          for name in $(echo $projects | jq -rc 'keys | join(" ")')
          do
            path=$(echo $projects | jq -rc --arg key "$name" '.[$key]')
            version=$(jq -rc '.version' $path/package.json | cut -d'-' -f1)
            version="$version${{ steps.suffix.outputs.value }}"
            projectName=$(jq -rc '.name' $path/package.json)
            context="{\"name\": \"$name\", \"path\": \"$path\", \"project\": \"$projectName\", \"version\": \"$version\"}"
            if [[ " $names " == *" $name "* ]]
            then
              json=$(echo $json | jq -rc --argjson context "$context" '. + [$context]')
            fi
            value=$(echo $value | jq -rc --argjson context "$context" --arg name "$name" '. + {($name): $context}')
            value=$(echo $value | jq -rc --argjson context "$context" --arg name "$projectName" '. + {($name): $context}')
          done
          echo value=$json >> $GITHUB_OUTPUT
          echo "projects=$value" >> $GITHUB_OUTPUT
    outputs:
      env: ${{ steps.env.outputs.value }}
      matrix: ${{ steps.matrix.outputs.value }}
      artifactory: ${{ steps.metadata.outputs.npm-target }}
      projects: ${{ steps.matrix.outputs.projects }}
      target: ${{ steps.metadata.outputs.target }}
  build:
    needs: context
    runs-on:
      - self-hosted
      - Linux
      - pmeig
    environment: ${{ needs.context.outputs.env }}
    env:
      PMEIG_TOKEN: ${{ secrets.PMEIG_TOKEN }}
    strategy:
      matrix:
        module: ${{ fromJSON(needs.context.outputs.matrix) }}
      max-parallel: 3
    steps:
      - name: checkout project
        uses: actions/checkout@v4
      - name: load secrets
        uses: pmeig/github-actions/actions/secret/vault@main
        id: vault
        with:
          cache: 'false'
          role-id: ${{ secrets.VAULT_ROLE_ID }}
          secret-id: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            pmeig/cicd/data/artifactory/jfrog/npm/writer user | ARTIFACTORY_USER;
            pmeig/cicd/data/artifactory/jfrog/npm/writer reference | ARTIFACTORY_PASSWORD;
            pmeig/cicd/data/artifactory/npm writer | REMOTE_TOKEN;
      - name: node setup
        uses: pmeig/github-actions/actions/node/setup@main
        id: node-setup
        with:
          remote-token: ${{ env.REMOTE_TOKEN }}
          branch: ${{ needs.context.outputs.target }}
      - name: find dependencies internal
        id: dependencies
        uses: pmeig/github-actions/actions/node/package/dependencies@main
        with:
          dev: true
          prefix: '@pmeig/'
          workspace: ${{ matrix.module.path }}
          subpath-resolver: |
            package=$(echo '${{ needs.context.outputs.projects }}' | jq -rc --arg key "$depend" '.[$key].path')
      - name: install dependencies
        id: projects
        run: |
          npm install
          if [ -n "${{ steps.dependencies.outputs.paths }}" ]
          then
            cwd=$(pwd)
            for path in ${{ steps.dependencies.outputs.paths }}
            do
              name=$(echo '${{ needs.context.outputs.projects }}' | jq -rc --arg key "$path" 'values | map(select(.path == $key)) | .[0].name')
              npm run ng -- build $name --configuration=production
              dist="dist/$name"
              cd $dist
              npm pack
              dist=$(pwd)
              mv *.tgz $name.tgz
              cd $cwd
              npm install $dist/$name.tgz
            done
          fi
      - name: build ${{ matrix.module.name }}
        id: build
        run: |
          workspace=$(pwd)
          path='${{ matrix.module.path }}'
          cd $path
          npm version --allow-same-version ${{ matrix.module.version }}
          cd $workspace
          npm run ng -- build ${{ matrix.module.name }} --configuration=production
          cd "dist/${{ matrix.module.name }}"
          dependencies=$(jq -rc '.dependencies // {}' package.json)
          peers=$(jq -rc '.peerDependencies // {}' package.json)
          for path in ${{ steps.dependencies.outputs.paths }}
          do
            project=$(echo '${{ needs.context.outputs.projects }}' | jq -rc --arg key "$path" 'values | map(select(.path == $key)) | .[0]')
            version=$(echo $project | jq -rc '.version')
            name=$(echo $project | jq -rc '.project')
            insert=''
            if [ ! "$(echo $dependencies | jq -rc --arg dep "$name" 'has($dep)')" == 'true' ]
            then
              jq -r --arg dep "$name" --arg version "^$version" '.dependencies += {($dep): $version}' package.json > package.new.json
            fi
            if [ ! "$(echo $peers | jq -rc --arg dep "$name" 'has($dep)')" == 'true' ]
            then
              jq -r --arg dep "$name" --arg version "^$version" '.peerDependencies += {($dep): $version}' package.json > package.new.json
            fi
            if [ -f package.new.json ]
            then
              mv package.new.json package.json
            fi
          done
          npm pack
          mv *.tgz ${{ matrix.module.name }}.tgz
          echo "pack=$(pwd)/${{ matrix.module.name }}.tgz" >> $GITHUB_OUTPUT
      - name: deploy on remote
        run: |
          options='--no-git-checks'
          if [ '${{ needs.context.outputs.env }}' != 'prod' ]
          then
            options="$options --tag snapshot"
          fi
          # pnpm publish ${{ steps.build.outputs.pack }} $options
          if [ '${{ needs.context.outputs.env }}' == 'prod' ]
          then
            npm config delete @pmeig:registry
            npm publish ${{ steps.build.outputs.pack }} --access public $options
          fi
  prepare-tag:
    if: ${{ needs.context.outputs.env == 'prod' }}
    needs:
      - build
      - context
    uses: ./.github/workflows/version.yml
    with:
      modules: ${{ needs.context.outputs.modules }}
  tag:
    needs:
      - prepare-tag
      - context
    runs-on:
      - self-hosted
      - Linux
      - pmeig
    strategy:
      max-parallel: 3
      matrix:
        module: ${{ fromJSON(needs.context.outputs.matrix) }}
    steps:
      - name: create tag
        uses: pmeig/github-actions/actions/github/release@main
        with:
          name: ${{ matrix.module.name }}_${{ matrix.module.version }}
          tag_name: ${{ matrix.module.name }}_${{ matrix.module.version }}
          branch: main
  tag-date:
    needs: tag
    runs-on:
      - self-hosted
      - Linux
      - pmeig
    steps:
      - name: tag
        id: tag
        run: |
          current=$(date +%Y_%m_%d)
          echo "value=release_$current" >> $GITHUB_OUTPUT
      - name: create tag
        uses: pmeig/github-actions/actions/github/release@main
        with:
          name: ${{ steps.tag.outputs.value }}
          tag_name: ${{ steps.tag.outputs.value }}
          branch: main


  next-feature:
    needs:
      - build
      - context
    if: ${{ needs.context.outputs.env == 'prod' }}
    environment: manual
    runs-on:
      - self-hosted
      - Linux
      - pmeig
    steps:
      - name: checkout project
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: push next feature
        id: staging
        run: |
          staging=''
          modules=''
          for module in $(echo '${{ needs.context.outputs.matrix }}' | jq -rc '.[]')
          do
            path=$(echo $module | jq -rc '.path')
            package="$path/package.json"
            release=$(echo $module | jq -rc '.version' | cut -d'.' -f2)
            version=$(jq -r '.version' $package)
            version=$(echo "$version" | cut -d'-' -f1)
            major=$(echo "$version" | cut -d'.' -f1)
            minor=$(echo "$version" | cut -d'.' -f2)

            if (( $minor == $release ))
            then
              json=$(jq -r --arg version "$major.$((minor + 1)).0-SNAPSHOT" '. + {"version": $version}' $path/package.json)
              modules="$modules $(echo $module | jq -rc '.name')"
              staging="$staging $package"
            fi
          done

          echo "modules=$modules" >> $GITHUB_OUTPUT
          echo "value=$staging" >> $GITHUB_OUTPUT
      - name: commit next feature
        if: ${{ steps.staging.outputs.value != '' }}
        uses: pmeig/github-actions/actions/github/push@main
        with:
          commit: "semver(minor): bump next feature for ${{ steps.staging.outputs.modules }}"
          stage: ${{ steps.staging.outputs.value }}
          mail: 'pierrick.workplace@gmail.com'
          user: 'pmeig'
